### ISSUE TITLE
Okta auth handler

### ISSUE THREAD

**Issue by JimmyMcBride** [Lambda-School-Labs/Labs25-Bridges_to_Prosperity-TeamA-fe#9]
AuthHandler function should redirect to `/404`. NotFoundPage should be edited to say:
```
404 page not found
if you think this is an error please contact your administrator
if you have an admin account login here (link to login page)
```

**Comment by Mosae** [comment]
404 page now has an option of directing back to the login page if user has admin creds.

**Comment by Mosae** [comment]
[](https://github.com/Lambda-School-Labs/Labs25-Bridges_to_Prosperity-TeamA-fe/issues/9#issue-677063872) Link to issue #15
